### ISSUE TITLE
Auth is broken after updating to v1.0

### ISSUE THREAD

**Issue by dmitryshagin** [fog/fog-packet#12]
What am I trying to do:
`packet_token = 'our valid token'` (checked via web version and with old version of gem
`compute = Fog::Compute::Packet.new(packet_token: packet_token)`
`compute.projects` (or any other command, like `compute.devices.create`, does not matter).
The result is always `RuntimeError: 401 {"error"=>"Invalid authentication token"}`. Same code works ok when Gemfile points to the master branch. Any ideas?

**Comment by vielmetti** [comment]
Thanks @dmitryshagin . 

Do you have two-factor auth turned on for that account, by any chance?

@edevenport can you take a look?

**Comment by edevenport** [comment]
@dmitryshagin - Good catch. An issue was missed with the token parameter because `fog-packet` also accepts the token as environment variable which was passing the mock and live tests. The token parameter has been fixed ( #13 ) and we tagged/published a new v1.0.1 release.

Can you please test again? Thank you!

**Comment by dmitryshagin** [comment]
Works now! Thaks for rapid fixing.
