### ISSUE TITLE
Unable to set project_ssh_keys

### ISSUE THREAD

**Issue by dmitryshagin** [fog/fog-packet#23]
Some things to mention:
*doc's are a bit inconsistent - in some places the description has correct ["string"], and in others, it's just "string" (e.g. this README)
*there is no description of how to use it, only one post that states both `key_id` or `user_id` are possible, but looks like this never works
*providing no keys leads to setting all available keys by default. Is it by design?
I tried to set almost everything as `project_ssh_keys` with no luck (key ID, user ID, key label, public key itself, the entire key struct as grabbed from project#ssh_keys, etc.). I'm always getting an error message stating that the provided key can't be used here.

**Comment by jasmingacic** [comment]
For details on how to use ssh keys please refer to this 
https://github.com/fog/fog-packet/blob/master/tests/packet/models/test_ssh_keys.rb
Can you provide me an example of what you are trying to do?

**Comment by dmitryshagin** [comment]
Managing keys itself is not an issue. I was trying to set some keys that would be passed to a created device.
```
connection = Fog::Compute::Packet.new(packet_token: "token")
project = connection.projects.first
ssh_keys = connection.ssh_keys.map { |key| key.id }
opts = { project_id: project.id,
      facility: "efw1",
      plan: "baremetal_0",
      operating_system: "coreos_stable",
      project_ssh_keys: ssh_keys,
      hostname: "hostname"
    }
connection.devices.create(opts)
```
Had no luck in figuring out any working combination to `project_ssh_keys`.

**Comment by edevenport** [comment]
@dmitryshagin I was testing your example and I was able to successfully create a server with `project_ssh_keys`. I essentially used your example code above, but made one change:

```
connection.ssh_keys.all(project.id).map { |key| key.id }
```

I have not tested all of the various scenarios, but I suspect `connection.ssh_keys` and `connection.ssh_keys.all` are retrieving `user_ssh_keys` only. If the project ID is included, then the `project_ssh_keys` are retrieved. After I adjusted your example, the server output resulted in:

```
    ...
    root_password=nil,
    hardware_reservation=nil,
    project_ssh_keys=["2747877c-31d2-4683-9ac8-6030dc68f0d1", "38f2f61a-e0d7-4753-bebb-b580da2d43ac"],
    user_ssh_keys=nil,
    ...
```

So the expected value is definitely a collection of strings (UUIDs to be exact).

@jasmingacic Can you update the README to indicate that `user_ssh_keys` and `project_ssh_keys` are collections of strings? The table just states `string`. We should also provide a README example showing server creation that includes SSH keys to make it more obvious.

Lastly, `providing no keys leads to setting all available keys by default. Is it by design?`

I noticed that all SSH keys are selected in the Packet UI by default when creating a new server. I had to deselect the SSH keys I didn't want to include. So I suspect this is indeed by design and happens through the API automatically. @jasmingacic Can you confirm?

**Comment by dmitryshagin** [comment]
Thanks, @edevenport, that helped.

**Comment by edevenport** [comment]
@jasmingacic Let's expand the documentation around SSH keys as suggested above. We should:

1. Indicate the value type is a collection. The description can explain a collection of SSH key UUID strings.

2. Update the create example to include either user and/or project SSH keys.

3. A note that indicates:

`compute.ssh_keys.all` is used with `user_ssh_keys`
`compute.ssh_keys.all(project.id)` is used with `project_ssh_keys`

Then I think we can close the ticket.

**Comment by edevenport** [comment]
The documentation has been updated to clarify usage around SSH keys.
