### ISSUE TITLE
Remove provisioning_events that not yet occured

### ISSUE THREAD

**Issue by dmitryshagin** [fog/fog-packet#5]
Just after provisioning server we have `provisioning_events` in responce that are useless and may be confusing. There is no useful data provided, and none of there events were fired at the moment, is there a reason for them to be shown to user?

```
provisioning_events=[
{"id"=>nil, "type"=>"provisioning.101", "body"=>"Provisioning started", "state"=>nil, "created_at"=>nil, "relationships"=>[], "ip"=>nil, "modified_by"=>nil, "interpolated"=>"Provisioning started"},
{"id"=>nil, "type"=>"provisioning.102", "body"=>"Network configured", "state"=>nil, "created_at"=>nil, "relationships"=>[], "ip"=>nil, "modified_by"=>nil, "interpolated"=>"Network configured"}
...
```
I'd suggest to show only events that actually took place.

**Comment by edevenport** [comment]
I'm not sure I understand. The response is returning exactly what the API is returning. If the response from the provider library is confusing, should the API be returning the response?

If `compute.devices.create` (POST) returns the provisioning events, it seems like they should be included. Whereas `compute.devices.get(device_id)` (GET) does not include the provisioning events since it was not a provisioning request. This seems like normal behavior.

**Comment by dmitryshagin** [comment]
Was a bit confusing to get it after post, but I can live with it :)
